ReactDOM.render(
<ul>
  <li>Mary</li>
  <li>Had</li>
  <li>A</li>
  <li>Little</li>
  <li>Lamb</li>
  <li>E</li>
  <li>I</li>
  <li>E</li>
  <li>I</li>
  <li>O</li>
  </ul>, 
  document.getElementById("root")
);